# Generated by Django 4.2.5 on 2023-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
